name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "qiujiandong1998@gmail.com"
          git config --global user.name "qiujiandong"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/nvim-lua/kickstart.nvim
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories --no-edit
          git push origin main
